Rewriting Closed Orbit Correction subsection and update new pdf file
lnls-fac/sands-adaptation pull request #1
Opened 2022-02-02 17:05 UTC by murilobalves

2022-02-02 17:08 UTC, xresende approved these changes

2022-02-02 17:15 UTC, vellosok75 approved these changes

2022-02-02 17:51 UTC, anacso17 approved these changes

2022-02-02 20:47 UTC, xresende approved these changes

2022-02-03 14:52 UTC, jquentino approved these changes

2022-02-03 16:23 UTC, LuanaVilela approved these changes

2022-02-03 20:31 UTC, fernandohds564 requested changes

2022-02-03 20:31 UTC, fernandohds564 commented on Chapter_2/2_10_DisturbedClosedOrbits.tex
> + The orbit distortion in the presence of field errors $\delta G(s_j)$ at different positions $s_j$ along the ring is given by:
in the presence of localized field errors

2022-02-03 20:31 UTC, fernandohds564 commented on Chapter_2/2_10_DisturbedClosedOrbits.tex
> +	where $u$ may represent the $x$ or $y$ coordinate.  The orbit distortions $\Delta u(s_i)$ can be measured in localized positions $s_i$, where the Beam Position Monitors (BPMs) are installed. The equ
It is not clear at this points that the field errors are created by the correctors, so it may confuse the reader to talk about response matrix now.

2022-02-03 20:31 UTC, fernandohds564 commented on Chapter_2/2_10_DisturbedClosedOrbits.tex
> + The orbit correction system in storage rings has BPMs and small dipoles magnets, called correctors or steering magnets, that steers the beam depending on orbit distortions measured by the BPMs. The
maybe this first sentence could be put in the beginning of the section to explain the idea...

2022-02-03 20:31 UTC, fernandohds564 commented on Chapter_2/2_10_DisturbedClosedOrbits.tex
> + $\mathrm{N}_{\mathrm{BPM}}$ is the number of BPMs, $\mathrm{N}_{\mathrm{CH}}$ is the number of horizontal correctors (CH) and $\mathrm{N}_{\mathrm{CV}}$ is the number of vertical correctors (CV). In
... the orbit distortion created by the kicks variation is given by (inline equation), ....

2022-02-03 20:31 UTC, fernandohds564 commented on Chapter_2/2_10_DisturbedClosedOrbits.tex
> + The pseudo-inverse of $\mathbf{M}^{\mathsf{T}}\mathbf{M}$ can be obtained, for example, with the method of Singular Value Decomposition (SVD). The SVD-based orbit correction is quite common in stora
(SVD) with a suitable choice of the singular values used in the inversion procedure.

2022-02-08 11:59 UTC, murilobalves commented
@fernandohds564 thank you for the suggestions, I applied them all, please take a look.

2022-02-08 14:50 UTC, fernandohds564 approved these changes

2022-02-23 13:24 UTC, merged