Gabrielrezende asc sands corrections
lnls-fac/sands-adaptation pull request #7
Opened 2022-05-11 17:28 UTC by Gabrielrezende-asc

I've made a few corrections in Sands adaptation, there is a comment for each correction describing the changes.

2022-05-11 18:47 UTC, xresende approved these changes

2022-05-11 18:50 UTC, anacso17 approved these changes

2022-05-11 19:45 UTC, murilobalves commented
> Here I just add the subscript "f" in the final value of y', this change was important because the equation 4.25 was a little "strange" when y' was equal y' times a factor, if it were correct delta p over p would be equal zero.

Hi @Gabrielrezende-asc, maybe you could attach screenshots of the changes in the PDF to facilitate the actual change in the document and also register the change in this PR.

2022-05-11 19:45 UTC, murilobalves approved these changes

2022-05-12 11:29 UTC, RafaelLyra8 approved these changes

2022-05-12 12:08 UTC, fernandohds564 approved these changes

2022-05-16 12:05 UTC, jquentino requested changes

2022-05-16 12:05 UTC, jquentino commented on Chapter_3/3_04_EnergyLossGain.tex
> +	V(\tau) = \widehat{V} \sin(\omega_{rf}(\tau-\tau_0))
Both signs gave the same result.

2022-05-16 12:07 UTC, jquentino approved these changes

2022-05-16 14:56 UTC, merged