Add authors
lnls-fac/sands-adaptation pull request #8
Opened 2022-05-11 18:56 UTC by xresende

2022-05-11 18:57 UTC, anacso17 approved these changes

2022-05-11 19:45 UTC, murilobalves approved these changes

2022-05-11 19:57 UTC, jquentino approved these changes

2022-05-12 11:29 UTC, RafaelLyra8 approved these changes

2022-05-12 12:03 UTC, fernandohds564 requested changes

2022-05-12 12:03 UTC, fernandohds564 commented on sands-adaptation.tex
> +    Gabriel Rezende de A. \\
Acho que deveria ser Gabriel R. De Ascenção, não?

2022-05-12 12:04 UTC, vellosok75 approved these changes

2022-05-12 13:00 UTC, Gabrielrezende-asc approved these changes

2022-05-20 13:55 UTC, xresende commented on sands-adaptation.tex
> +    Gabriel Rezende de A. \\
sim. tive o cuidado de olhar o nome completo antes de criar o PR. mas olhei na planilha do RH (PUE). obviamente estava errada...

2022-05-20 18:06 UTC, fernandohds564 approved these changes

2022-05-25 18:35 UTC, merged